openapi: 3.0.0
info:
  title: Mortgage API
  version: 1.0.0
  description: mortgage service api

servers:
  - url: http://localhost:8080

paths:
  /mortgage/request/{requestId}:
    get:
      summary: Get Mortgage Request Info
      description: Retrieve the processing info of a mortgage request by its ID.
      parameters:
        - in: path
          name: requestId
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the mortgage request
      responses:
        '200':
          description: Successful response with mortgage request info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MortgageRequestInfoDto'
        '400':
          description: Invalid request ID
        '404':
          description: Mortgage request not found
        '500':
          description: Internal server error

  /mortgage/request:
    post:
      summary: Requests mortgage offer preparation
      description: Requests mortgage offer preparation
      operationId: mortgageRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MortgageRequestDto'
      responses:
        '201':
          description: Mortgage request placed sucessfuly
        '400':
          description: Request error
        '403':
          description: Log in for access
        '500':
          description: Server error]


components:
  schemas:
    MortgageRequestDto:
      type: object
      properties:
        customerId:
          type: string
          format: uuid
        durationInMonths:
          type: integer
        amount:
          type: number

    MortgageRequestInfoDto:
      type: object
      properties:
        status:
          type: string
          enum:
            - PENDING
            - APPROVED
            - REJECTED
          description: The current state of the mortgage request
        offerId:
          type: string
          format: uuid
          description: The UUID of the offer related to the mortgage request
      required:
        - status
        - offerId




